import pytest
from ex2 import encrypt, freq_dist_attack

@pytest.mark.parametrize("texto_original, chave_correta", [
    ("viajarparapraiasdocalor", "aaaa"),
    ("amanhateremosreuniaoimportante", "aaaaaaa"),
    ("cafecomleiteehmeubebidafavorita", "aaaaaaaaaa"),
    ("jogosolimpicossaoemocionantes", "aaaaaaaaaaaaaaa"),
    ("chuvasdeveraoenchemasruas", "aaa"),
    ("compreiosingredientesdopudim", "aaaaaa"),
    ("festadeaniversariofoiumsucesso", "aaaaaaaaaaa"),
    ("pratiqueesportesparavivermais", "aaaaaaaaaaaaaaaaa"),
    ("mercadoestacheiocomenlatados", "aaaaaaaaa"),
    ("gatinhosadoraveisbrincandonaarea", "aa"),
    ("maratonadefilmescomecanasexta", "aaaaaaaa"),
    ("ciclismoeumodosustentaveldemover", "aaaaaaaaaaaa"),
    ("limpezageralnacasadoferiado", "aaaaa"),
    ("almocodedomingotemcarneassada", "aaaaaaaaaaaaaa"),
    ("bibliotecaspublicassaoessenciais", "aaaaaaaaaaaaa"),
    ("jogodotabuleiroestaquente", "aaaaaa"),
    ("musicasnovasestaoemtodasaslistas", "aaaaaaaaaaaaaaaaaaa"),
    ("comidarapidaepraticaeconveniente", "aaaaaaaaaaaaaaa"),
    ("cachorroslatemparaodesconhecidos", "aaaaaaaa"),
    ("domingodetempofamiliadiversao", "aaaaaaaaaaaaaaaaaaaa"),
    ("acampamentonaserrafritanotemperatura", "aaaaaaaaaaaaaaaaaaaaaaa"),
    ("estacoesdotremtemhorariosfixos", "aaaaa"),
    ("camisetacomdesenhododinofofa", "aaaaaaaaa"),
    ("sorvetedefrutassobremesaideal", "aaaaaaaaaaaaaaaaaa"),
    ("roupasdeinvernosaoquentinhas", "aaaaaaa"),
    ("florestasdensaosemprecombarulhos", "aaaaaaaaaaaaaaaaaaaaaa"),
    ("cadernoderecadosfoiencontrado", "aaaa"),
    ("macaeverdeebemsuave", "aaaaaaaaaaaa"),
    ("barcospesqueirossaomuitoativos", "aaaaaa"),
    ("bicicletaeumesmomeiotransporte", "aaaaaaaaaaaaa"),
    ("jardinagemetranquilizanteehrelaxante", "aaaaaaaaaaaaaaaaa"),
    ("livrosdeaventuraempolgantes", "aaaaaaaaaaaaaaa"),
    ("cafeteriasurbanassaocharmosas", "aaaaaaaaaaa"),
    ("mapasdetesourosdesenhadosempapel", "aaaaaaaaaa"),
    ("noitefriaechuvosaacendeolareira", "aaaaaaaaaaaaaaaaaaa"),
    ("avidadesemtrabalhoepaz", "aaaaaaaa"),
    ("despertadortocoucedomadrugada", "aaaaaaaaaaaaaa"),
    ("planetasdouniversoparecemgigantes", "aaaaaaa"),
    ("estrelasbrilhantesnaceuazul", "aaaaaa"),
    ("museusguardamartefatosantigos", "aaa"),
    ("galaxiassaoimensasemisteriosas", "aaaaaaaaaaaaaaaaaaaaaaaaa"),
    ("caminhadaspelamontanhaesaoideais", "aaaaaaaaaaaaaaa"),
    ("temperaturacaiudepoisdochave", "aaaaa"),
    ("filmesdesuspensetiramofolego", "aaaaaaaa"),
    ("passarinhoscantamnofinaldatarde", "aaaaaaaaaaaaaaaaaaaa"),
    ("pianistaspraticamtodososdias", "aaaaaaaaaaaaaaaaaaaaaa"),
    ("bolofofocomgostosodelimaoficadelicia", "aaaaaaaaaaa"),
    ("labirintosemfimdesafiajogadores", "aaaaaaaaa"),
    ("turistasadmiramacidadehistorica", "aaaaaaaaaaaa"),
    ("meiascoloridassaoamadasporcriancas", "aaaaaaaaaaaaaa"),
    ("veraoechuvosoalaganovamente", "aaaaaaaaaaaaaaaaaa"),
    ("zezeviuazebra", "aaa"),
    ("socorro", "aaaaa"),
    ("socorro", "aa"),
    ("socorro", "a"),
    ("palmeiras", "aa"),
    ("palmeiras", "aaa"),
    ("quandosurgeoalviverdeimponentenogramadoemquealutaoaguardasabebemoquevempelafrentequeadurezadoprelionaotardaeopalmeirasnoardordapartidatransformandoalealdadeempadraosabesemprelevardevencidaemostrarquedefatoecampeaodefesaqueninguempassalinhaatacantederacatorcidaquecantaevibradefesaqueninguempassalinhaatacantederacatorcidaquecantaevibrapornossoalviverdeinteiroquesabeserbrasileiroostentandoasuafibra", "aaa"),
    ("quandosurgeoalviverdeimponentenogramadoemquealutaoaguardasabebemoquevempelafrentequeadurezadoprelionaotardaeopalmeirasnoardordapartidatransformandoalealdadeempadraosabesemprelevardevencidaemostrarquedefatoecampeaodefesaqueninguempassalinhaatacantederacatorcidaquecantaevibradefesaqueninguempassalinhaatacantederacatorcidaquecantaevibrapornossoalviverdeinteiroquesabeserbrasileiroostentandoasuafibra", "aaaaaa"),
    ("quandosurgeoalviverdeimponentenogramadoemquealutaoaguardasabebemoquevempelafrentequeadurezadoprelionaotardaeopalmeirasnoardordapartidatransformandoalealdadeempadraosabesemprelevardevencidaemostrarquedefatoecampeaodefesaqueninguempassalinhaatacantederacatorcidaquecantaevibradefesaqueninguempassalinhaatacantederacatorcidaquecantaevibrapornossoalviverdeinteiroquesabeserbrasileiroostentandoasuafibra", "aaaaaaaaaaaaaaa"),
    ("anoticiaeumformatodedivulgacaodeumacontecimentopormeiosjornalisticoseamateriaprimadojornalismonormalmentereconhecidacomoalgumdadooueventosocialmenterelevantequemerecepublicacaoemummeiodecomunicacaosocialfatospoliticossociaiseconomicosculturaisnaturaiseoutrospodemsernoticiaseafetaremindividuosougrupossignificativosparaumdeterminadoveiculodeimprensaanoticiapodeserdefinidacomoumprodutosocialmenteconstruidopoiseresultadodasposicoessociaisdeindividuosegruposenvolvidoscomaproducaojornalisticaepelaspropriasfontesqueatuamcomodefinidoresprimariosdoseventosanoticiaeumacondensacaodessesdeterminantesemumprodutosocioculturalessencialnaconstrucaodosprocessosconteudoserelacoessociais", "aaaaaa"),
    ("anoticiaeumformatodedivulgacaodeumacontecimentopormeiosjornalisticoseamateriaprimadojornalismonormalmentereconhecidacomoalgumdadooueventosocialmenterelevantequemerecepublicacaoemummeiodecomunicacaosocialfatospoliticossociaiseconomicosculturaisnaturaiseoutrospodemsernoticiaseafetaremindividuosougrupossignificativosparaumdeterminadoveiculodeimprensaanoticiapodeserdefinidacomoumprodutosocialmenteconstruidopoiseresultadodasposicoessociaisdeindividuosegruposenvolvidoscomaproducaojornalisticaepelaspropriasfontesqueatuamcomodefinidoresprimariosdoseventosanoticiaeumacondensacaodessesdeterminantesemumprodutosocioculturalessencialnaconstrucaodosprocessosconteudoserelacoessociais", "aaaaaaa"),
    ("anoticiaeumformatodedivulgacaodeumacontecimentopormeiosjornalisticoseamateriaprimadojornalismonormalmentereconhecidacomoalgumdadooueventosocialmenterelevantequemerecepublicacaoemummeiodecomunicacaosocialfatospoliticossociaiseconomicosculturaisnaturaiseoutrospodemsernoticiaseafetaremindividuosougrupossignificativosparaumdeterminadoveiculodeimprensaanoticiapodeserdefinidacomoumprodutosocialmenteconstruidopoiseresultadodasposicoessociaisdeindividuosegruposenvolvidoscomaproducaojornalisticaepelaspropriasfontesqueatuamcomodefinidoresprimariosdoseventosanoticiaeumacondensacaodessesdeterminantesemumprodutosocioculturalessencialnaconstrucaodosprocessosconteudoserelacoessociais", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
])

def test_freq_dist_attack(texto_original, chave_correta):
    cifra = encrypt(texto_original, chave_correta)

    attempts = freq_dist_attack(cifra, testing=True)

    assert len(chave_correta) in attempts
