import pytest
from enc_dec import encrypt
from freq_dist import freq_dist_attack

@pytest.mark.parametrize("texto_original, chave_correta", [
    ("viajarparapraiasdocalor", 4),
    ("amanhateremosreuniaoimportante", 7),
    ("cafecomleiteehmeubebidafavorita", 10),
    ("jogosolimpicossaoemocionantes", 15),
    ("chuvasdeveraoenchemasruas", 3),
    ("compreiosingredientesdopudim", 6),
    ("festadeaniversariofoiumsucesso", 11),
    ("pratiqueesportesparavivermais", 17),
    ("mercadoestacheiocomenlatados", 9),
    ("gatinhosadoraveisbrincandonaarea", 2),
    ("maratonadefilmescomecanasexta", 8),
    ("ciclismoeumodosustentaveldemover", 12),
    ("limpezageralnacasadoferiado", 5),
    ("almocodedomingotemcarneassada", 14),
    ("bibliotecaspublicassaoessenciais", 13),
    ("jogodotabuleiroestaquente", 6),
    ("musicasnovasestaoemtodasaslistas", 19),
    ("comidarapidaepraticaeconveniente", 21),
    ("cachorroslatemparaodesconhecidos", 16),
    ("domingodetempofamiliadiversao", 20),
    ("acampamentonaserrafritanotemperatura", 23),
    ("estacoesdotremtemhorariosfixos", 5),
    ("camisetacomdesenhododinofofa", 9),
    ("sorvetedefrutassobremesaideal", 18),
    ("roupasdeinvernosaoquentinhas", 7),
    ("florestasdensaosemprecombarulhos", 22),
    ("cadernoderecadosfoiencontrado", 4),
    ("macaeverdeebemsuave", 12),
    ("barcospesqueirossaomuitoativos", 6),
    ("bicicletaeumesmomeiotransporte", 13),
    ("jardinagemetranquilizanteehrelaxante", 17),
    ("livrosdeaventuraempolgantes", 15),
    ("cafeteriasurbanassaocharmosas", 11),
    ("mapasdetesourosdesenhadosempapel", 10),
    ("noitefriaechuvosaacendeolareira", 19),
    ("avidadesemtrabalhoepaz", 8),
    ("despertadortocoucedomadrugada", 14),
    ("planetasdouniversoparecemgigantes", 7),
    ("estrelasbrilhantesnaceuazul", 6),
    ("museusguardamartefatosantigos", 3),
    ("galaxiassaoimensasemisteriosas", 25),
    ("caminhadaspelamontanhaesaoideais", 21),
    ("temperaturacaiudepoisdochave", 5),
    ("filmesdesuspensetiramofolego", 16),
    ("passarinhoscantamnofinaldatarde", 20),
    ("pianistaspraticamtodososdias", 22),
    ("bolofofocomgostosodelimaoficadelicia", 11),
    ("labirintosemfimdesafiajogadores", 9),
    ("turistasadmiramacidadehistorica", 12),
    ("meiascoloridassaoamadasporcriancas", 14),
    ("veraoechuvosoalaganovamente", 18),
    ("zezeviuazebra", 3),
    ("socorro", 5),
    ("socorro", 2),
    ("socorro", 1),
    ("palmeiras", 2),
    ("palmeiras", 3),
    ("quandosurgeoalviverdeimponentenogramadoemquealutaoaguardasabebemoquevempelafrentequeadurezadoprelionaotardaeopalmeirasnoardordapartidatransformandoalealdadeempadraosabesemprelevardevencidaemostrarquedefatoecampeaodefesaqueninguempassalinhaatacantederacatorcidaquecantaevibradefesaqueninguempassalinhaatacantederacatorcidaquecantaevibrapornossoalviverdeinteiroquesabeserbrasileiroostentandoasuafibra", 3),
    ("quandosurgeoalviverdeimponentenogramadoemquealutaoaguardasabebemoquevempelafrentequeadurezadoprelionaotardaeopalmeirasnoardordapartidatransformandoalealdadeempadraosabesemprelevardevencidaemostrarquedefatoecampeaodefesaqueninguempassalinhaatacantederacatorcidaquecantaevibradefesaqueninguempassalinhaatacantederacatorcidaquecantaevibrapornossoalviverdeinteiroquesabeserbrasileiroostentandoasuafibra", 6),
    ("quandosurgeoalviverdeimponentenogramadoemquealutaoaguardasabebemoquevempelafrentequeadurezadoprelionaotardaeopalmeirasnoardordapartidatransformandoalealdadeempadraosabesemprelevardevencidaemostrarquedefatoecampeaodefesaqueninguempassalinhaatacantederacatorcidaquecantaevibradefesaqueninguempassalinhaatacantederacatorcidaquecantaevibrapornossoalviverdeinteiroquesabeserbrasileiroostentandoasuafibra", 15),
    ("quaseninguemvequantomaisotempopassamaisaumentaagracaemvoceocoracaodisparatropecaquaseparaencaronoteubeijoqueaquimevejointeiroeuameitever", 22),
    ("anoticiaeumformatodedivulgacaodeumacontecimentopormeiosjornalisticoseamateriaprimadojornalismonormalmentereconhecidacomoalgumdadooueventosocialmenterelevantequemerecepublicacaoemummeiodecomunicacaosocialfatospoliticossociaiseconomicosculturaisnaturaiseoutrospodemsernoticiaseafetaremindividuosougrupossignificativosparaumdeterminadoveiculodeimprensaanoticiapodeserdefinidacomoumprodutosocialmenteconstruidopoiseresultadodasposicoessociaisdeindividuosegruposenvolvidoscomaproducaojornalisticaepelaspropriasfontesqueatuamcomodefinidoresprimariosdoseventosanoticiaeumacondensacaodessesdeterminantesemumprodutosocioculturalessencialnaconstrucaodosprocessosconteudoserelacoessociais", 6),
    ("anoticiaeumformatodedivulgacaodeumacontecimentopormeiosjornalisticoseamateriaprimadojornalismonormalmentereconhecidacomoalgumdadooueventosocialmenterelevantequemerecepublicacaoemummeiodecomunicacaosocialfatospoliticossociaiseconomicosculturaisnaturaiseoutrospodemsernoticiaseafetaremindividuosougrupossignificativosparaumdeterminadoveiculodeimprensaanoticiapodeserdefinidacomoumprodutosocialmenteconstruidopoiseresultadodasposicoessociaisdeindividuosegruposenvolvidoscomaproducaojornalisticaepelaspropriasfontesqueatuamcomodefinidoresprimariosdoseventosanoticiaeumacondensacaodessesdeterminantesemumprodutosocioculturalessencialnaconstrucaodosprocessosconteudoserelacoessociais", 7),
    ("anoticiaeumformatodedivulgacaodeumacontecimentopormeiosjornalisticoseamateriaprimadojornalismonormalmentereconhecidacomoalgumdadooueventosocialmenterelevantequemerecepublicacaoemummeiodecomunicacaosocialfatospoliticossociaiseconomicosculturaisnaturaiseoutrospodemsernoticiaseafetaremindividuosougrupossignificativosparaumdeterminadoveiculodeimprensaanoticiapodeserdefinidacomoumprodutosocialmenteconstruidopoiseresultadodasposicoessociaisdeindividuosegruposenvolvidoscomaproducaojornalisticaepelaspropriasfontesqueatuamcomodefinidoresprimariosdoseventosanoticiaeumacondensacaodessesdeterminantesemumprodutosocioculturalessencialnaconstrucaodosprocessosconteudoserelacoessociais", 30),
])

def test_freq_dist_attack(texto_original, chave_correta):
    cifra = encrypt(texto_original, chave_correta)

    attempts = freq_dist_attack(cifra, testing=True)

    # verifica se a chave correta está entre as tentativas
    assert texto_original in attempts
